import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyDocuments,reviewDocuments,documentSchema} from '../features/documents/model';
import {FIELDS} from '../lib/types';

const lines=['Shipper: NORTHSTAR PAPER LTD','Consignee: HARBOR BOOKS LTD','Notify Party: HARBOR BOOKS LTD','Port of Loading: PORT KLANG','Port of Discharge: SINGAPORE','Container Count: 2','Gross Weight: 24000 kg'];
const doc=(heading:string)=>({name:heading==='SHIPPING INSTRUCTION'?'si.pdf':'bl.docx',format:heading==='SHIPPING INSTRUCTION'?'PDF':'DOCX',method:heading==='SHIPPING INSTRUCTION'?'pdf-text':'docx-text',segments:[{location:'Page 1',text:heading+'\n'+lines.join('\n')}],sha256:'a'.repeat(64),ocrConfidence:null,warning:null});
const pair=()=>[doc('SHIPPING INSTRUCTION'),doc('DRAFT BILL OF LADING')];
test('upload uses frozen extraction and finds only the actual changed field',()=>{const d=pair();d[1].segments[0].text=d[1].segments[0].text.replace('Consignee: HARBOR BOOKS LTD','Consignee: WESTPORT BOOKS LTD');const c=verifyDocuments(d,'upload_test');assert.equal(c.status,'MISMATCH');assert.deepEqual(c.defect_fields,['consignee']);assert(c.comparisons.every(x=>x.si.evidence&&x.bl.evidence));});
test('OCR remains review-required regardless of recognition score',()=>{const d=pair();Object.assign(d[0],{method:'ocr',ocrConfidence:100});const c=verifyDocuments(d,'upload_test');assert.equal(c.status,'NEEDS_REVIEW');assert.equal(c.has_defect,false);assert.equal(c.documents[0].ocrConfidence,100);});
test('unreadable extraction never becomes a verified match',()=>{const d=pair();d[0].segments=[];d[0].method='unreadable';assert.equal(verifyDocuments(d,'upload_test').status,'NEEDS_REVIEW');});
test('upload validation bounds content and rejects image text-layer forgery',()=>{assert.throws(()=>documentSchema.parse({...doc('SHIPPING INSTRUCTION'),format:'PNG'}));assert.throws(()=>documentSchema.parse({...doc('SHIPPING INSTRUCTION'),name:'../secret'}));assert.throws(()=>verifyDocuments(pair().concat(pair()),'upload_test'));assert.throws(()=>documentSchema.parse({...doc('SHIPPING INSTRUCTION'),segments:[{location:'x',text:'x'.repeat(50001)}]}));});
test('OCR finalization requires source attestation and complete normalized values',()=>{const d=pair();d[0].method='ocr';const c=verifyDocuments(d,'upload_test');const values=Object.fromEntries(c.comparisons.map(x=>[x.field,{si:x.si.raw,bl:x.bl.raw}])) as Record<typeof FIELDS[number],{si:string;bl:string}>;const input={id:'upload_test',revision:0,decision:'confirm' as const,reviewer:'Test reviewer',note:'All values checked against the supplied originals.',values};assert.throws(()=>reviewDocuments(c,input),/original/);assert.equal(reviewDocuments(c,{...input,sourceConfirmed:true}).reviewed,true);values.container_count.si='';assert.throws(()=>reviewDocuments(c,{...input,sourceConfirmed:true}),/Resolve/);});
test('wrong documents cannot bypass review by changing category',()=>{const d=pair();d[0].segments[0].text='COMMERCIAL INVOICE\n'+lines.join('\n');const c=verifyDocuments(d,'upload_test');assert.throws(()=>reviewDocuments(c,{id:'upload_test',revision:0,decision:'confirm',category:'GENERAL',reviewer:'Test',note:'Confirming unsupported documents is not allowed.',values:{} as never,sourceConfirmed:true}),/readable SI/);});
