import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize} from '../lib/normalization';
import {extract,docType} from '../lib/extraction';
import {classify} from '../lib/classification';
import {processEmail,processCorpus} from '../lib/pipeline';
import {applyReview} from '../lib/review';
import {compare} from '../lib/comparison';
import {submission,validateSubmission} from '../lib/reporting';
import type {Corpus,SourceDocument,Email,Field} from '../lib/types';
import corpus from '../data/corpus.json';
const text=`Shipper: Example Trading Ltd\n  12 Ocean Road, Unit 4\nConsignee: Buyer Ltd\nNotify Party: Buyer Ltd\nPOL: SINGAPORE (SGSIN)\nPOD: SYDNEY, AUSTRALIA\nNumber of Containers: 3\nGross Weight (KG): 22,000 KG`;
const doc=(name:string,body:string):SourceDocument=>({path:'attachments/'+name,name,format:'TXT',method:'txt',text:body,segments:[{location:'Text document',text:body}],error:null,sha256:'test-fixture'});
const si=doc('instruction.txt','SHIPPING INSTRUCTION\n'+text),bl=doc('draft.txt','BILL OF LADING (DRAFT)\n'+text);
const email:Email={email_id:'new-shipment-random-id',from:'operator@example.com',subject:'Invoice discussion',body:'Please compare the SI against the draft BL before release.',attachments:[si.path,bl.path]};
const c:Corpus={emails:[email],documents:{[si.path]:si,[bl.path]:bl}};
test('formatting normalization preserves address and entity tokens',()=>{assert.equal(normalize('shipper','Example Trading Ltd. | 12 Ocean Road; Unit 4'),normalize('shipper','EXAMPLE TRADING LTD\n12 OCEAN ROAD, UNIT 4'));assert.notEqual(normalize('shipper','Example Ltd, 12 Ocean Road'),normalize('shipper','Example Ltd, 13 Ocean Road'));assert.notEqual(normalize('consignee','Alpha LLC'),normalize('consignee','Beta LLC'));});
test('unit conversion, grouping, and ambiguous numbers',()=>{assert.equal(normalize('gross_weight_kg','22 MT'),22000);assert.equal(normalize('gross_weight_kg','22,000.50 KGS'),22000.5);assert.equal(normalize('gross_weight_kg','22.000,50 KG'),22000.5);assert.equal(normalize('gross_weight_kg','22 000 KG'),22000);assert.equal(normalize('gross_weight_kg','1,5 KG'),null);assert.equal(normalize('container_count',"3 x 40'HC"),3);assert.equal(normalize('container_count','-1'),null);});
test('placeholder values never become a mismatch',()=>{for(const raw of ['???','____MT','TBA',''])assert.equal(normalize('port_of_loading',raw),null);});
test('body intent wins over misleading invoice subject',()=>{assert.equal(classify(email).category,'BL_COMPARISON');});
test('new SI containing draft BL and invoice mentions remains SI request',()=>{assert.equal(classify({...email,attachments:[],subject:'SI needed',body:'Please find Shipping instruction.\nShipper: Example\nConsignee: Buyer\nDocuments required: invoice and original BL. Please revert with draft BL once available.'}).category,'SI_REQUEST');});
test('quoted phishing does not override current message routing',()=>{assert.equal(classify({...email,attachments:[],body:'Daily berthing report. No action required.\nFrom: scammer\nYou have won a prize, claim your gift.'}).category,'GENERAL');});
test('role detection uses content not filename',()=>{assert.equal(docType(si),'SI');assert.equal(processEmail(email,c).status,'OK');assert.equal(processEmail(email,c).explanation,'No mismatch detected');});
test('synonym labels preserve multiline address evidence',()=>{const x=extract(doc('x.txt',text.replace('Shipper:','Shipper/Exporter:').replace('Consignee:','To the Order of:').replace('POL:','Load Port:')));assert.equal(x.shipper.raw,'Example Trading Ltd\n12 Ocean Road, Unit 4');assert.equal(x.container_count.normalized,3);assert.match(x.shipper.location,/line 1/);});
test('only the changed field is flagged',()=>{const changed=doc('draft.txt','BILL OF LADING (DRAFT)\n'+text.replace('Containers: 3','Containers: 4'));assert.deepEqual(processEmail(email,{...c,documents:{...c.documents,[bl.path]:changed}}).defect_fields,['container_count']);});
test('different explicit port codes are not normalized away',()=>{const a=extract(si),b=extract(doc('b.txt',text.replace('SGSIN','MYPKG')));assert.equal(compare(a,b).find(c=>c.field==='port_of_loading')?.status,'MISMATCH');});
test('contradictory repeated labels escalate instead of taking last',()=>{const x=extract(doc('x.txt',text+'\nGross Weight: 23,000 KG'));assert.equal(x.gross_weight_kg.normalized,null);});
test('missing, wrong-type, unreadable, blank each get separate reason',()=>{
 assert.equal(processEmail({...email,attachments:[]},c).review_reason,'missing_attachment');
 assert.equal(processEmail(email,{...c,documents:{...c.documents,[bl.path]:doc('draft.txt','COMMERCIAL INVOICE\nSeller: Example')}}).review_reason,'wrong_doc_type');
 assert.equal(processEmail(email,{...c,documents:{...c.documents,[bl.path]:{...bl,error:'No readable text'}}}).review_reason,'unreadable');
 assert.equal(processEmail(email,{...c,documents:{...c.documents,[si.path]:doc('instruction.txt','SHIPPING INSTRUCTION\n'+text.replace('22,000 KG','TBA'))}}).review_reason,'missing_value');
});
test('future draft request is visibly awaiting documents, exported OK',()=>{const r=processEmail({...email,attachments:[],body:'Please send the draft BL for checking.'},c);assert.equal(r.operationalStatus,'AWAITING_DOCUMENTS');assert.equal(r.status,'OK');assert.equal(r.has_defect,false);});
test('review requires complete evidence, preserves original and recomputes',()=>{const original=processEmail(email,c);const values=Object.fromEntries(original.comparisons.map(x=>[x.field,{si:x.si.raw,bl:x.bl.raw}])) as Record<Field,{si:string;bl:string}>;assert.throws(()=>applyReview(original,{id:email.email_id,revision:0,decision:'confirm',values,note:'',reviewer:''}));const reviewed=applyReview(original,{id:email.email_id,revision:0,decision:'confirm',values,note:'Both original source documents checked in full.',reviewer:'Test reviewer'});assert.equal(reviewed.reviewed,true);assert.equal(original.reviewed,undefined);assert.deepEqual(reviewed.documents,original.documents);assert.equal(reviewed.status,'OK');});
test('full dataset covers exact official schema without reference answers',()=>{const cases=processCorpus(corpus);assert.equal(cases.length,520);assert.equal(Object.keys(corpus.documents).length,250);assert.equal(validateSubmission(submission(cases),corpus.emails.map(e=>e.email_id)),true);assert.equal(cases.filter(c=>c.status==='NEEDS_REVIEW').every(c=>!c.has_defect&&!c.defect_fields.length),true);});
