'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,LayoutDashboard,Inbox,ScanLine,Users,FileClock,Workflow,ArrowUpRight,ArrowRight,Search,Download,RefreshCw,Check,AlertTriangle,FileText,ChevronRight,ChevronLeft,LoaderCircle,X,Paperclip,CheckCheck,Clock3,ExternalLink} from 'lucide-react';
import {CATEGORIES,FIELDS,LABELS,type Case,type Field} from '@/lib/types';
import {submission} from '@/lib/reporting';
import UploadWorkspace from '@/features/documents/UploadWorkspace';
type View='Dashboard'|'Smart inbox'|'Verification'|'Human review'|'Reports & audit'|'Processing'|'Upload documents';
const nav=[['Dashboard',LayoutDashboard],['Smart inbox',Inbox],['Verification',ScanLine],['Human review',Users],['Reports & audit',FileClock],['Processing',Workflow],['Upload documents',FileText]] as const;
const friendly=(s:string)=>({BL_COMPARISON:'BL comparison',SI_REQUEST:'SI request',INVOICE_QUERY:'Invoice query',GENERAL:'General',SPAM:'Spam',OK:'Verified',MISMATCH:'Mismatch',NEEDS_REVIEW:'Needs review',AWAITING_DOCUMENTS:'Awaiting documents',CLASSIFIED:'Classified'}[s]||s.replaceAll('_',' '));
function Badge({status}:{status:string}){return <span className={'badge '+status.toLowerCase()}>{status==='OK'||status==='MATCH'?<Check size={13}/>:status==='NEEDS_REVIEW'?<AlertTriangle size={13}/>:null}{status==='MATCH'?'Match':friendly(status)}</span>;}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type Audit={id:string;action:string;emailId?:string;note:string;actor:string;createdAt:string};
export default function Home(){
 const [view,setView]=useState<View>('Dashboard'),[cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState('Loading inbox'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [query,setQuery]=useState(''),[category,setCategory]=useState('ALL'),[status,setStatus]=useState('ALL'),[page,setPage]=useState(0),[evidence,setEvidence]=useState<Field|null>(null),[tab,setTab]=useState('comparison');
 const [editing,setEditing]=useState(false),[note,setNote]=useState(''),[reviewer,setReviewer]=useState(''),[values,setValues]=useState<Record<string,{si:string;bl:string}>>({}),[audit,setAudit]=useState<Audit[]>([]),[persistent,setPersistent]=useState(false),[reviewCategory,setReviewCategory]=useState<string>('BL_COMPARISON');
 async function load(){setBusy('Loading inbox');try{const r=await fetch('/api/cases');if(!r.ok)throw Error('Inbox is unavailable. Please retry.');const d=await r.json() as {cases:Case[];audit:Audit[];persistent:boolean;error?:string;message?:string};setCases(d.cases);setAudit(d.audit||[]);setPersistent(d.persistent);setError('');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 useEffect(()=>{load();const h=decodeURIComponent(location.hash.slice(1));if(nav.some(n=>n[0]===h))setView(h as View);},[]);
 function navigate(v:View){setView(v);location.hash=v;setPage(0);setQuery('');setCategory('ALL');setStatus('ALL');setEditing(false);}
 function open(c:Case){setSelected(c.email.email_id);setEvidence(null);setTab('comparison');navigate('Verification');}
 const active=cases.find(c=>c.email.email_id===selected)||cases.find(c=>c.status==='MISMATCH')||cases[0];
 const comparisons=cases.filter(c=>c.category==='BL_COMPARISON'),verified=comparisons.filter(c=>['OK','MISMATCH'].includes(c.operationalStatus)),mismatches=cases.filter(c=>c.status==='MISMATCH'),reviews=cases.filter(c=>c.operationalStatus==='NEEDS_REVIEW'),waiting=cases.filter(c=>c.operationalStatus==='AWAITING_DOCUMENTS');
 const filtered=cases.filter(c=>(view!=='Human review'||c.operationalStatus==='NEEDS_REVIEW')&&(category==='ALL'||c.category===category)&&(status==='ALL'||c.operationalStatus===status)&&(`${c.email.subject} ${c.email.from} ${c.email.email_id}`.toLowerCase().includes(query.toLowerCase())));
 async function action(path:string,body:unknown,message:string){setBusy(message);setError('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {cases:Case[];audit:Audit[];persistent:boolean;error?:string;message?:string};if(!r.ok)throw Error(d.error||'Operation failed');if(d.cases)setCases(d.cases);if(d.audit)setAudit(d.audit);setNotice(d.message||'Saved successfully');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy('');}}
 function beginReview(){if(!active)return;setValues(Object.fromEntries(active.comparisons.map(c=>[c.field,{si:c.si.raw,bl:c.bl.raw}])));setNote('');setReviewCategory(active.category);setEditing(true);}
 async function finalize(decision:string){if(!active)return;const ok=await action('/api/review',{id:active.email.email_id,revision:active.revision||0,decision,values,note,reviewer,category:reviewCategory},'Saving review');if(ok)setEditing(false);}
 function table(rows:Case[],compact=false){return <div className="table-scroll"><table><thead><tr><th>Message / shipment</th>{!compact&&<th>Category</th>}<th>Status</th>{!compact&&<th>Routing signal</th>}<th aria-label="Open case"></th></tr></thead><tbody>{rows.map(c=><tr key={c.email.email_id} onClick={()=>open(c)}><td><button className="subject" onClick={e=>{e.stopPropagation();open(c);}}>{c.email.subject}</button><span className="meta">{c.email.email_id.replace('email_','#')} <span>·</span> {c.email.from} {c.email.attachments.length>0&&<><Paperclip size={12}/> {c.email.attachments.length}</>}</span></td>{!compact&&<td><span className="category">{friendly(c.category)}</span></td>}<td><Badge status={c.operationalStatus}/></td>{!compact&&<td><span className="confidence">{Math.round(c.classification.confidence*100)}/100 <i style={{width:c.classification.confidence*40}}/></span></td>}<td><ChevronRight size={17}/></td></tr>)}</tbody></table>{!rows.length&&<div className="empty"><Inbox/><h3>No cases found</h3><p>Try a different filter or search.</p></div>}</div>;}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#Dashboard" onClick={()=>navigate('Dashboard')}><span className="brand-icon"><ShieldCheck size={24}/></span><span>CargoGuard<span className="brand-sub">DOCUMENT VERIFICATION</span></span></a><div className="workspace-label">OPERATIONS WORKSPACE</div><nav>{nav.map(([v,Icon])=><button key={v} onClick={()=>navigate(v)} className={view===v?'active':''}><Icon size={19}/><span>{v}</span>{v==='Human review'&&reviews.length>0&&<b>{reviews.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="dataset-label"><span className="tiny-dot"/> Official dataset</div><p>{cases.length || '…'} messages · 7 verification fields</p><div className="profile"><span>CG</span><div>Hackathon workspace<small>Synthetic data · isolated session</small></div></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><strong>{view}</strong></div><div className="topbar-right"><span className="mode"><span className="tiny-dot"/> Local processing</span><span className="avatar">CG</span></div></header><main>
 {error&&<div className="banner error" role="alert"><AlertTriangle size={18}/><span>{error}</span><button onClick={load}>Retry</button><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {notice&&<div className="banner success" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="page-heading"><div><div className="eyebrow">SHIPPING OPERATIONS <span>/</span> CARGOGUARD</div><h1>{view==='Dashboard'?'Shipping Document Verification':view==='Verification'?'Verification workspace':view==='Processing'?'From inbox to confidence.':view}</h1><p>{view==='Dashboard'?'Evidence-backed shipping document verification for the Averis × Monash Hackathon 2026':view==='Verification'?'Compare the draft against the shipping instruction. Keep the evidence in view.':view==='Human review'?'Resolve uncertainty before a shipment moves forward.':view==='Smart inbox'?'Mixed messages, clear intent. Find the requests that need your attention.':view==='Processing'?'A transparent pipeline with a human decision wherever evidence falls short.':view==='Upload documents'?'Extract real documents, inspect evidence, and verify with the frozen engine.':'Verification outcomes and a traceable record of every review.'}</p></div><div className="heading-actions">{view==='Upload documents'?null:view==='Dashboard'||view==='Processing'?<button className="primary" disabled={!!busy} onClick={()=>action('/api/process',{},`Processing ${cases.length} emails`)}><RefreshCw size={16} className={busy?'spin':''}/> Process inbox</button>:<button className="secondary" disabled={!cases.length} onClick={()=>download('submission.json',submission(cases))}><Download size={16}/> Export submission</button>}</div></div>
 {busy&&<div className="loading" role="status"><LoaderCircle size={16} className="spin"/>{busy}…</div>}
 {!cases.length&&!busy?<div className="empty"><Inbox size={32}/><h3>Inbox is unavailable</h3><button className="primary" onClick={load}>Load dataset</button></div>:null}
 {view==='Upload documents'&&<UploadWorkspace/>}
 {view==='Dashboard'&&cases.length>0&&<>
 <div className="judge-path"><span>Inbox → routing → source evidence → seven-field check → human review → report</span><button className="secondary" onClick={()=>{const c=cases.find(c=>c.status==='MISMATCH');if(c)open(c);}}>Open a discrepancy</button><button className="primary" onClick={()=>navigate('Upload documents')}>Upload your SI / BL</button></div>
 <div className="stats"><div className="stat"><span>Total messages <Inbox size={18}/></span><strong>{cases.length}</strong><small>{comparisons.length} BL comparison requests</small></div><div className="stat"><span>Documents verified <ShieldCheck size={18}/></span><strong>{verified.length}<em>pairs</em></strong><small>All seven fields checked</small></div><div className="stat accent-stat"><span>Discrepancies detected <ScanLine size={18}/></span><strong>{mismatches.length}</strong><small>Cases requiring an amendment</small></div><div className="stat"><span>Human review <Users size={18}/></span><strong>{reviews.length}<em className="amber">action needed</em></strong><small>Evidence needs a second look</small></div></div>
 <div className="pipeline-strip"><span className="strip-label"><Workflow size={18}/> Inbox overview</span><div><strong>{cases.length}</strong> classified</div><ArrowRight/><div><strong>{comparisons.length}</strong> comparison requests</div><ArrowRight/><div><strong>{verified.length}</strong> verified</div><span className="strip-end">{waiting.length} awaiting documents</span></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Needs your attention <span className="count">{reviews.length+mismatches.length}</span></h2><p>Exceptions first. Open a case to inspect the evidence.</p></div><button className="text-button" onClick={()=>navigate('Human review')}>Review queue <ArrowUpRight size={16}/></button></div>{table([...reviews,...mismatches].slice(0,5),true)}</section><section className="panel distribution"><div className="panel-heading"><div><h2>Inbox composition</h2><p>Classification across all messages</p></div></div><div className="distribution-total"><strong>{cases.length}</strong><span>messages classified</span></div><div className="stacked-bar">{CATEGORIES.map((cat,i)=><span key={cat} style={{width:`${cases.filter(c=>c.category===cat).length/cases.length*100}%`,background:['#0d7469','#466984','#b59264','#a9b9c7','#d6dfe5'][i]}}/>)}</div>{CATEGORIES.map((cat,i)=><button className="category-count" key={cat} onClick={()=>{navigate('Smart inbox');setCategory(cat);}}><span style={{background:['#0d7469','#466984','#b59264','#a9b9c7','#d6dfe5'][i]}}/>{friendly(cat)}<b>{cases.filter(c=>c.category===cat).length}</b></button>)}</section></div>
 <div className="insight"><ShieldCheck size={27}/><div><h3>Confidence starts with evidence.</h3><p>Uncertain values stay in review. Every comparison links back to its source document.</p></div><button className="text-button" onClick={()=>navigate('Processing')}>Explore the pipeline <ArrowRight size={17}/></button></div>
 </>}
 {(view==='Smart inbox'||view==='Human review')&&<section className="panel"><div className="filters"><div className="search"><Search size={17}/><input aria-label="Search inbox" placeholder="Search subject, sender, or email ID" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><select aria-label="Filter category" value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="ALL">All categories</option>{CATEGORIES.map(c=><option key={c} value={c}>{friendly(c)}</option>)}</select>{view!=='Human review'&&<select aria-label="Filter status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="ALL">All statuses</option>{['OK','MISMATCH','NEEDS_REVIEW','AWAITING_DOCUMENTS','CLASSIFIED'].map(s=><option key={s} value={s}>{friendly(s)}</option>)}</select>}<span className="result-count">{filtered.length} messages</span></div>{table(filtered.slice(page*12,page*12+12))}<div className="pagination"><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/12))} · No received timestamps supplied</span><button className="secondary" disabled={page===0} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/> Previous</button><button className="secondary" disabled={(page+1)*12>=filtered.length} onClick={()=>setPage(page+1)}>Next <ChevronRight size={16}/></button></div></section>}
 {view==='Verification'&&active&&<>
 <section className="panel case-heading"><div><div className="case-id">{active.email.email_id.replace('email_','CASE ')} <Badge status={active.operationalStatus}/>{active.reviewed&&<span className="badge ok"><CheckCheck size={13}/> Human confirmed</span>}</div><h2>{active.email.subject}</h2><p>{active.email.from} <span>·</span> {active.documents.length} attachments <span>·</span> Routing signal {Math.round(active.classification.confidence*100)}/100 · heuristic</p></div><div className="case-actions"><button className="secondary" disabled={!!busy} onClick={()=>action('/api/retry',{id:active.email.email_id,revision:active.revision||0},'Retrying case')}><RefreshCw size={15}/> Retry</button>{<button className="primary" onClick={beginReview}><Users size={16}/> Review case</button>}</div></section>
 <div className={'outcome '+active.status.toLowerCase()}>{active.status==='OK'?<ShieldCheck size={21}/>:<AlertTriangle size={21}/>}<div><strong>{active.explanation}</strong><p>{active.status==='NEEDS_REVIEW'?`Reason: ${active.review_reason?.replaceAll('_',' ')}. No defect is asserted until evidence is sufficient.`:active.operationalStatus==='AWAITING_DOCUMENTS'?'This is an open request, not a completed verification.':'The Shipping Instruction is the reference for all comparisons.'}</p></div></div>
 <div className="tabs"><button className={tab==='comparison'?'selected':''} onClick={()=>setTab('comparison')}>Field comparison <span>7</span></button><button className={tab==='documents'?'selected':''} onClick={()=>setTab('documents')}>Source documents <span>{active.documents.length}</span></button><button className={tab==='email'?'selected':''} onClick={()=>setTab('email')}>Email & routing</button></div>
 {tab==='comparison'&&<section className="panel comparison-panel"><div className="compare-head"><div>VERIFICATION FIELD</div><div><span className="document-label">SI</span> Shipping instruction <small>REFERENCE DOCUMENT</small></div><div><span className="document-label bl">BL</span> Draft bill of lading <small>DOCUMENT TO VERIFY</small></div><div>RESULT</div></div>{active.comparisons.map(c=><button key={c.field} className={'compare-row '+(c.status==='MISMATCH'?'different':'')+(evidence===c.field?' chosen':'')} onClick={()=>setEvidence(evidence===c.field?null:c.field)}><div className="field-name">{LABELS[c.field]}<small>View source evidence <ArrowUpRight size={12}/></small></div><div>{c.si.raw||<em>Not available</em>}</div><div>{c.bl.raw||<em>Not available</em>}</div><div><Badge status={c.status}/></div></button>)}{!active.comparisons.length&&<div className="empty"><FileText/><h3>No comparison performed</h3><p>{active.explanation}</p></div>}<div className="comparison-footer"><ShieldCheck size={15}/> Case, punctuation, label synonyms, and units normalized conservatively.</div></section>}
 {evidence&&tab==='comparison'&&<section className="panel evidence-panel"><div className="panel-heading"><h2>Source evidence · {LABELS[evidence]}</h2><button className="icon-button" aria-label="Close evidence" onClick={()=>setEvidence(null)}><X size={18}/></button></div><div className="evidence-grid">{['si','bl'].map(side=>{const c=active.comparisons.find(c=>c.field===evidence);const value=side==='si'?c?.si:c?.bl;return <div key={side}><div className="eyebrow">{side.toUpperCase()} · {value?.location}</div><pre>{value?.evidence||'No source evidence available'}</pre><p>Normalized: <code>{value?.normalized??'Unresolved'}</code></p>{value?.issue&&<p className="amber">{value.issue}</p>}</div>;})}</div></section>}
 {tab==='documents'&&<div className="documents-grid">{active.documents.map(d=><section className="panel document" key={d.path}><div className="panel-heading"><div><span className="document-label">{d.format}</span><h3>{d.name}</h3></div><a className="text-button" href={'/documents/'+encodeURIComponent(d.name)} target="_blank" rel="noreferrer">Original <ExternalLink size={15}/></a></div>{d.error&&<div className="outcome needs_review">{d.error}</div>}<pre>{d.text||'No readable text. Open the original for manual review.'}</pre><div className="document-hash">SHA-256 · {d.sha256}</div></section>)}{!active.documents.length&&<div className="empty">No attachments received.</div>}</div>}
 {tab==='email'&&<div className="evidence-grid"><section className="panel email-body"><h2>Original message</h2><pre>{active.email.body}</pre></section><section className="panel email-body"><h2>Routing decision</h2><Badge status={active.category}/><p>{active.classification.method} · {Math.round(active.classification.confidence*100)}/100 routing signal</p>{active.classification.reasons.map(r=><p key={r}>{r}</p>)}<small>Confidence is a heuristic signal, not a calibrated probability.</small></section></div>}
 {editing&&<section className="panel review-form"><div className="panel-heading"><div><h2>Human review</h2><p>Only transcribe values supported by a readable source. Corrections retain the original evidence.</p></div><button className="icon-button" onClick={()=>setEditing(false)} aria-label="Close review"><X/></button></div><div className="review-category"><label>Email category <select aria-label="Review category" value={reviewCategory} onChange={e=>setReviewCategory(e.target.value)}>{CATEGORIES.map(c=><option key={c} value={c}>{friendly(c)}</option>)}</select></label></div><div className="review-fields">{(reviewCategory==='BL_COMPARISON'?FIELDS:[]).map(f=><div key={f}><label>{LABELS[f]}</label><input aria-label={'SI '+LABELS[f]} placeholder="SI value" value={values[f]?.si||''} onChange={e=>setValues({...values,[f]:{...values[f],si:e.target.value}})}/><input aria-label={'BL '+LABELS[f]} placeholder="BL value" value={values[f]?.bl||''} onChange={e=>setValues({...values,[f]:{...values[f],bl:e.target.value}})}/></div>)}</div><div className="review-notes"><label>Reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Your name"/></label><label>Review note / evidence reference<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain the correction and identify the supporting source."/></label></div><div className="review-buttons"><button className="secondary" disabled={!!busy} onClick={()=>finalize('reject')}>Reject result · keep in review</button><button className="primary" disabled={!!busy} onClick={()=>finalize('confirm')}><CheckCheck size={16}/> Confirm & finalize</button></div>{!persistent&&<p className="amber">Persistent review storage is not connected yet.</p>}</section>}
 </>}
 {view==='Reports & audit'&&<><div className="report-summary"><section className="panel report-card"><FileText size={28}/><div><h2>Official submission</h2><p>All {cases.length} emails in the required JSON schema.</p></div><button className="primary" onClick={()=>download('submission.json',submission(cases))}><Download size={16}/> Export JSON</button></section><section className="panel report-card"><FileClock size={28}/><div><h2>Discrepancy report</h2><p>Field-level results, source evidence, and review notes.</p></div><button className="secondary" onClick={()=>download('verification-report.json',cases.filter(c=>c.category==='BL_COMPARISON'))}><Download size={16}/> Export report</button></section></div><section className="panel"><div className="panel-heading"><div><h2>Audit trail</h2><p>Saved processing and reviewer actions in this workspace</p></div><span className="badge general">{audit.length} events</span></div>{audit.length?audit.map(a=><div className="audit-row" key={a.id}><span className="audit-icon"><FileClock size={17}/></span><div><strong>{a.action} {a.emailId&&`· ${a.emailId}`}</strong><p>{a.note}</p><small>{a.actor} · {new Date(a.createdAt).toLocaleString()}</small></div></div>):<div className="empty"><Clock3/><h3>No saved actions yet</h3><p>Process the inbox or complete a review to record an event.</p></div>}</section></>}
 {view==='Processing'&&<><div className="system-banner"><div><span className="eyebrow">HYBRID DOCUMENT PIPELINE</span><h2>Automate the routine.<br/>Escalate the uncertain.</h2><p>Local processing is active. No external AI service is required for this dataset.</p></div><div className="system-fact"><strong>7</strong><span>fields checked<br/>for every document pair</span></div></div><div className="pipeline-cards">{[['01','Ingest & classify','Read email content and attachment context. Combine intent descriptions with action signals.'],['02','Parse & extract','TXT, PDF, Word, and Excel adapters retain source text and page, table, or sheet evidence.'],['03','Normalize & compare','Align semantic labels, parse units, preserve names and addresses. SI stays the reference.'],['04','Review & report','Uncertainty enters the review queue. Reviewer corrections are validated, audited, and exported.']].map(([n,t,d])=><section className="panel pipeline-card" key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></section>)}</div><section className="panel system-settings"><h2>Runtime & reliability</h2><dl><div><dt>Processing engine</dt><dd>Curated lexical intent ensemble + deterministic field extraction</dd></div><div><dt>Learned AI</dt><dd>Tesseract LSTM recognizes printed English text in scanned PDFs and images, on your device.</dd></div><div><dt>External language model</dt><dd>Optional classifier adapter; not configured or claimed as active in this demo.</dd></div><div><dt>Source formats</dt><dd>TXT · PDF · DOCX · XLSX</dd></div><div><dt>Scanned documents</dt><dd>English LSTM OCR in Upload documents; every OCR result requires human confirmation</dd></div><div><dt>Persistent state</dt><dd>{persistent?'Cloudflare D1 · review and audit storage':'Connecting to storage'}</dd></div><div><dt>Official self-evaluation</dt><dd>Export submission.json, then submit to the official local service. No score is assumed.</dd></div></dl></section></>}
 <footer><span>CargoGuard <b> | </b> Shipping Document Verification</span><span>Averis × Monash Hackathon 2026</span></footer>
 </main></div></div>;
}
